### ISSUE TITLE
Windows10 ERROR Backup Read Exception

### ISSUE THREAD

**Issue by DM-F** [MaxiHuHe04/iTunes-Backup-Explorer#5] opened 2022-04-25 17:14 UTC
Hi, I'm trying to read a backup on an external HD it's not encrypted and I get this error.

me.maxih.itunes_backup_explorer.api.BackupReadException:
java.util.NoSuchElementException: No value present

same error on Manifest.db or .plist

Files are there and if manually add the extension it works fine but I hoped this could save me some time. Can you please help me?

**Comment by MaxiHuHe04** [comment] 2022-04-26 14:42
Hey @DM-F,
Could you please launch the program using ``java -jar itunes-backup-explorer-1.1.jar`` in the terminal and post the whole console output after you tried to open the backup?

**Comment by AkaiiKitsune** [comment] 2022-05-05 21:27
Same issue here, Error is as follows : 

May 05, 2022 11:24:37 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @161eefae'
me.maxih.itunes_backup_explorer.api.BackupReadException: me.maxih.itunes_backup_explorer.api.BackupReadException: java.util.NoSuchElementException: No value present
        at me.maxih.itunes_backup_explorer.api.ITunesBackup.loadManifest(ITunesBackup.java:86)
        at me.maxih.itunes_backup_explorer.api.ITunesBackup.<init>(ITunesBackup.java:71)
        at me.maxih.itunes_backup_explorer.api.ITunesBackup.lambda$getBackups$0(ITunesBackup.java:33)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at me.maxih.itunes_backup_explorer.api.ITunesBackup.getBackups(ITunesBackup.java:43)
        at me.maxih.itunes_backup_explorer.ui.WindowController.loadBackups(WindowController.java:137)
        at me.maxih.itunes_backup_explorer.ui.WindowController.initialize(WindowController.java:78)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2673)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2516)
        at me.maxih.itunes_backup_explorer.ITunesBackupExplorer.start(ITunesBackupExplorer.java:21)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: me.maxih.itunes_backup_explorer.api.BackupReadException: java.util.NoSuchElementException: No value present
        at me.maxih.itunes_backup_explorer.api.BackupManifest.<init>(BackupManifest.java:49)
        at me.maxih.itunes_backup_explorer.api.ITunesBackup.loadManifest(ITunesBackup.java:84)
        ... 32 more
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377)
        at me.maxih.itunes_backup_explorer.api.BackupManifest.<init>(BackupManifest.java:36)
        ... 33 more

**Comment by Rikysonic** [comment] 2022-05-10 08:25
I had the same error on my WIndows 10 machine.
I investigated a bit and I made it work with little fixes. Now I've opened a PR to MaxiHuHe04 and, if he agrees, he could release a new version :)

**Comment by MaxiHuHe04** [comment] 2022-05-17 15:21
Should be fixed now in [v1.2](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/releases/tag/v1.2).

**Closed by MaxiHuHe04** 2022-05-17 15:21 UTC
Labels: bug
